Repository pushpendra-91/freecodecamp_sol, pull requests merged in 2021-09, with the labels that each got.

#1 Footer
  landing page/index.html
  landing page/style.css
Labels: Hacktoberfest

#2 Portfolio descriptions has been changed
  portfolio/index.html
Labels: hacktoberfest-accepted

#3 portfolio added
  landing page/index.html
Labels: Hacktoberfest, hacktoberfest-accepted
